# Generated by Django 5.2.1 on 2025-06-07 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PuntoOficina',
            new_name='PuntosOficinasModel',
        ),
    ]
