# Generated by Django 5.2.2 on 2025-06-07 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_puntooficina_puntosoficinasmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MunicipioColombia',
            new_name='MunicipiosColombiaModel',
        ),
    ]
