# Generated by Django 5.2.2 on 2025-06-07 22:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_municipiocolombia_municipioscolombiamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipioscolombiamodel',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=3116),
        ),
    ]
